os:
  - linux
  - windows
language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
